### ISSUE TITLE
정보 수정 시 정보 수정완료 alert 띄우기

### ISSUE THREAD

**Issue by tae0code** [TeamCrazyPerformance/IsEmpty#28]
profile/info에서 POST로 정보 수정을 요청하고 정보가 수정 되었으면 alert를 띄워주고 싶은데 방법을 모르겠어요..
다른 페이지로 임시적으로 넘어가서 alert을 띄우는것 밖에 생각이 안나요ㅠㅠ 조언좀

**Comment by hyesun03** [comment]
커스텀으로 팝업만드는거 말고 당장 alert만 띄워줄거면.. 그 submit버튼에 click이벤트가 발생하면 form 값 확인해서 변경되었으면 alert띄워주면될거같어

**Comment by tae0code** [comment]
그러면 그렇게 일단 수정해둘게요 ㅋㅋ
